name: Deploy Gently Rotting Site
run-name: Deploy Site 🚀
on: 
  push:
     branches:
       - main
permissions:
  id-token: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mkdir public
      - run: docker compose run quartz-builder
      - run: tar -cvJf gently-rotting-site-${{ github.sha }}.tar.xz public
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gently-rotting-site
          path: public
      - name: Copy tar to Lightsail instance
        uses: appleboy/scp-action@master
        with:
          host: gentlyrotting.online
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          source: gently-rotting-site-*.tar.xz
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}/archive"
      - name: Extract tar on Lightsail instance
        uses: appleboy/ssh-action@master
        with:
          host: gentlyrotting.online
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          script: |
            file=$(ls -Art archive | tail -n1)
            tar xvf archive/${file}
