name: Build and Deploy Gently Rotting Site
run-name: Build🛠️ and Deploy🚀
on:
  push:
permissions:
  id-token: write
  contents: read
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mkdir public
      - name: Build site
        run: docker compose run quartz-builder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gently-rotting-site
          path: public
  Deploy-Site:
    if: github.ref == 'refs/heads/main'
    needs: Build-Site
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve built site
        uses: actions/download-artifact@v4
        with:
          name: gently-rotting-site
          path: public
      - name: Package site as tar
        run: tar -cvJf gently-rotting-site-${{ github.sha }}.tar.xz public
      - name: Copy tar to Lightsail instance
        uses: appleboy/scp-action@master
        with:
          host: gentlyrotting.online
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          source: gently-rotting-site-*.tar.xz
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}/archive"
      - name: Extract tar on Lightsail instance
        uses: appleboy/ssh-action@master
        with:
          host: gentlyrotting.online
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          script: |
            file=$(ls -Art archive | tail -n1)
            tar xvf archive/${file}
